Repository zowe/tn3270-ng2, pull requests merged in 2025-05, with the labels that each got.

#95 Modify Reply with actual CCSID
  CHANGELOG.md
  README.md
  config/storageDefaults/sessions/_keySequences.json
  webClient/src/lib/js/tn3270.js
  webClient/webpack.config.js
Labels: size/S

#98 Create .npmrc
  .npmrc
Labels: size/XS

#99 Create .npmrc
  .npmrc
Labels: size/XS

#97 Update README - Usage missing
  README.md
Labels: size/XS

#96 V2: Reply CCSID
  CHANGELOG.md
  README.md
  config/storageDefaults/sessions/_keySequences.json
  webClient/src/lib/js/tn3270.js
  webClient/webpack.config.js
Labels: size/S

#100 Users/zhou/enhance backspace behavior
  CHANGELOG.md
  webClient/src/app/app.component.css
  webClient/src/app/app.component.html
  webClient/src/app/app.component.ts
  webClient/src/app/terminal.config.ts
  webClient/src/app/terminal.ts
  webClient/src/lib/js/tn3270.js
Labels: size/M
